#!/usr/bin/env bash
# Generate config/litellm.yaml from config/models.tsv.
# Usage: scripts/gen-config.sh [catalog.tsv] [output.yaml]
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
catalog="${1:-$here/config/models.tsv}"
out="${2:-$here/config/litellm.yaml}"
version="$(cat "$here/VERSION" 2>/dev/null || echo dev)"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
cat <<EOF
# GENERATED by scripts/gen-config.sh from config/models.tsv. Do not edit by hand.
# Upstream bases and keys come from the environment that claude-go-ctl starts
# the proxy with (see ~/.config/claude-go/env):
#   CLAUDE_GO_ANTHROPIC_BASE  e.g. https://opencode.ai/zen/go     (Anthropic Messages)
#   CLAUDE_GO_OPENAI_BASE     e.g. https://opencode.ai/zen/go/v1  (Chat Completions / Responses)
#   OPENCODE_GO_API_KEY       your Go key
#   LITELLM_MASTER_KEY        local key Claude Code uses to talk to this proxy

model_list:
EOF

awk -F'\t' -v ua="claude-go/${version}" '
  /^[[:space:]]*#/ || NF < 3 { next }
  $3 != "yes" { next }
  {
    id = $1; proto = $2
    if (proto == "messages")       { model = "anthropic/" id;           base = "os.environ/CLAUDE_GO_ANTHROPIC_BASE" }
    else if (proto == "chat")      { model = "openai/" id;              base = "os.environ/CLAUDE_GO_OPENAI_BASE" }
    else if (proto == "responses") { model = "openai/responses/" id;    base = "os.environ/CLAUDE_GO_OPENAI_BASE" }
    else { printf("unknown protocol %s for %s\n", proto, id) > "/dev/stderr"; exit 1 }
    printf("  - model_name: %s\n", id)
    printf("    litellm_params:\n")
    printf("      model: %s\n", model)
    printf("      api_base: %s\n", base)
    printf("      api_key: os.environ/OPENCODE_GO_API_KEY\n")
    printf("      extra_headers:\n")
    printf("        User-Agent: \"%s\"\n", ua)
    printf("    model_info:\n")
    printf("      claude_go_protocol: %s\n", proto)
  }
' "$catalog"

cat <<'EOF'

litellm_settings:
  # Claude Code sends Anthropic-only params (thinking, effort, ...). Drop what a
  # translated backend does not understand instead of failing the request.
  drop_params: true
  # LiteLLM 1.10x sends /v1/messages for every openai/* model through the
  # Responses API. Go's chat models only speak Chat Completions, so opt out;
  # models listed with the openai/responses/ prefix still use Responses.
  use_chat_completions_url_for_anthropic_messages: true
  # Claude Code already retries (up to 10 times, honouring retry-after). Proxy
  # retries multiply with those: at 2, one turn against a rate-limited model
  # made 33 upstream requests. Let Claude Code own retrying.
  num_retries: 0
  request_timeout: 600

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  # Forward client x-* headers upstream. This carries Claude Code's
  # x-claude-code-session-id and the x-opencode-session header that the
  # claude-go wrapper adds, which Go uses for routing and prompt caching.
  forward_client_headers_to_llm_api: true
EOF
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
n=$(grep -c '^  - model_name:' "$out")
echo "wrote $out ($n models)"
